
###
GET http://localhost:4000/health-check


###
GET http://localhost:4000/meetings


###
POST http://localhost:4000/meetings
Content-Type: application/json

{
  "name": "ArgoCD",
  "category_id": "cc6e3bcd-b2cd-4dcf-9999-9bac3ae6850d",
  "date": "2023-05-02T01:12:42.702Z"
}

###
GET http://localhost:4000/meetings/2aceed8f-c1ba-4882-ae96-7f53a6b89e50


###
DELETE http://localhost:4000/meetings/da42f238-1761-46a7-9ef7-b7a86b779f27
