
###
GET http://localhost:4000/health-check


###
GET http://localhost:4000/meetings


###
POST http://localhost:4000/meetings
Content-Type: application/json

{
  "name": "Docker to everyone",
  "category_id": "2b41b2d9-49d3-44a8-8a0c-0ba84cb8c359",
  "date": "2022-09-02T01:12:42.702Z"
}

###
GET http://localhost:4000/meetings/984c39d7-70e0-49c0-9969-2495bc152959


###
DELETE http://localhost:4000/meetings/da42f238-1761-46a7-9ef7-b7a86b779f27


###

