
###
GET http://localhost:4001/health-check

###
GET http://localhost:4001/categories

###
POST http://localhost:4001/categories
Content-Type: application/json

{
    "name": "Programming"
}

###
GET http://localhost:4001/categories/bdd56403-3597-4471-bb66-a88316fd506f


###
DELETE http://localhost:4001/categories/bdd56403-3597-4471-bb66-a88316fd506f


###
PATCH http://localhost:4001/categories/8b2469da-f0d8-4584-ae46-5be2493e102e
Content-Type: application/json

{
    "name": "Technology demo"
}


