
###
GET http://localhost:4001/health-check


###
POST http://localhost:4001/categories
Content-Type: application/json

{
    "name": "Programming"
}


###
GET http://localhost:4001/categories


###
GET http://localhost:4001/categories/0b0a9864-a156-4298-8990-c16c893759c2


###
DELETE http://localhost:4001/categories/e9d96edf-7716-4730-8251-db0cea13a49e


###
PATCH http://localhost:4001/categories/2b41b2d9-49d3-44a8-8a0c-0ba84cb8c359
Content-Type: application/json

{
    "name": "Technology 10"
}


